name: Release to GCP

on:
  push:
    branches:
      - add-boba-devnet

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      DOCKER_REGISTRY: us-docker.pkg.dev

    steps:
      - uses: 'actions/checkout@v4'

      - name: Authenticate to GCP using Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: 'true'
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'

      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud services list

      - name: Push to GCP
        run: |
          gcloud auth configure-docker ${{ env.DOCKER_REGISTRY }}
          docker build . -f proposer/op/Dockerfile.op_proposer -t ${{ env.DOCKER_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/op-succinct-proposer:${{ github.ref_name }}
          docker push ${{ env.DOCKER_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/op-succinct-proposer:${{ github.ref_name }}