name: Release to GCP

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      DOCKER_REGISTRY: us-docker.pkg.dev

    steps:
    - uses: 'actions/checkout@v4'

    - name: Authenticate to GCP using Workload Identity Federation
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT }}'

    - name: Push to GCP
      run: |
        gcloud auth configure-docker $DOCKER_REGISTRY
        docker build . -f proposer/op/Dockerfile.op_proposer -t $$DOCKER_REGISTRY/${{ secrets.GCP_PROJECT_ID }}/op-succinct-proposer:${{ github.ref_name }} .
        docker push $$DOCKER_REGISTRY/${{ secrets.GCP_PROJECT_ID }}/op-succinct-proposer:${{ github.ref_name }}